BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS "dev";

CREATE TABLE IF NOT EXISTS "dev".accounts (
    id     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    address VARCHAR(255) NOT NULL
);

INSERT INTO "dev".accounts (address) VALUES ('0110590920000001234567');


COMMIT;
